### ISSUE TITLE
Use CloudTrail events for Trusted Advisor checks

### ISSUE THREAD

**Issue by ianshward** [mapbox/patrol-rules-aws#104]
CloudTrail now has Trusted Advisor checks https://aws.amazon.com/about-aws/whats-new/2016/11/trusted-advisor-enables-automated-actions-and-custom-notifications/ 

It looks like we could switch the Trusted Advisor rules to use CloudTrail events instead of API calls to Trusted Advisor.

**Comment by jakepruitt** [comment]
This was done!
